[project]
name = "quasi-newton"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "psutil>=7.0.0",
    "ruff>=0.11.8",
    "scipy>=1.15.2",
]
